# Generated by Django 5.0.2 on 2024-02-15 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipe_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe_id',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe_api.recipe'),
        ),
        migrations.AlterField(
            model_name='recipesteps',
            name='recipe_id',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe_api.recipe'),
        ),
        migrations.AlterField(
            model_name='useringredients',
            name='ingredient_id',
            field=models.ForeignKey(db_column='ingredient_id', on_delete=django.db.models.deletion.CASCADE, related_name='customusers', to='recipe_api.ingredients'),
        ),
        migrations.AlterField(
            model_name='useringredients',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL),
        ),
    ]
