# Generated by Django 5.0.2 on 2024-02-08 20:05
import environ
from django.db import migrations

def add_user(apps, schema_editor):
    from django.contrib.auth import get_user_model
    env = environ.Env()
    EMAIL = env('ADMIN_EMAIL')
    PASSWORD = env('ADMIN_PASSWORD')

    CustomUser = get_user_model()
    admin = CustomUser.objects.filter(email=EMAIL).first()

    if admin is None:
        admin = CustomUser.objects.create_superuser(EMAIL, PASSWORD)
        admin.save()
    else:
        print("Admin already exists")

class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
