# Generated by Django 5.0.2 on 2024-02-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0003_alter_recipe_user_id_and_more'),
        ('recipe_api', '0004_recipe_api'),
    ]

    operations = [
    ]
