# Generated by Django 5.0.2 on 2024-02-15 18:47
import environ
from django.db import migrations
from django.conf import settings

def create_data(apps, schema_editor):
    env = environ.Env()
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User.objects.get(email=env('ADMIN_EMAIL'))

    Recipe = apps.get_model('recipe_api', 'Recipe')
    newRecipe = Recipe(name="Chocolate Chip Cookies", user_id=user)
    newRecipe.save()

    Ingredients = apps.get_model('recipe_api', 'Ingredients')
    Ingredients(ingredient_name="flour", brand="King Arthur").save()
    Ingredients(ingredient_name="granulated sugar", brand="Domino").save()
    Ingredients(ingredient_name="salted butter", brand="Land O'Lakes").save()
    Ingredients(ingredient_name="chocolate chips", brand="Ghirardelli").save()
    Ingredients(ingredient_name="vanilla extract", brand="McCormick").save()
    Ingredients(ingredient_name="baking soda", brand="Arm & Hammer").save()
    Ingredients(ingredient_name="salt", brand="Morton").save()
    Ingredients(ingredient_name="egg", brand="Eggland's Best").save()
    Ingredients(ingredient_name="light brown sugar", brand="Domino").save()
    Ingredients(ingredient_name="baking powder", brand="Clabber Girl").save()

    UserIngredients = apps.get_model('recipe_api', 'UserIngredients')
    UserIngredients.objects.create(user_id=user, ingredient_id=Ingredients.objects.get(ingredient_name="flour"), amount=2, unit="cups")
    UserIngredients.objects.create(user_id=user, ingredient_id=Ingredients.objects.get(ingredient_name="salt"), amount=0.75, unit="cups")
    UserIngredients.objects.create(user_id=user, ingredient_id=Ingredients.objects.get(ingredient_name="egg"), amount=1, unit="cup")
    UserIngredients.objects.create(user_id=user, ingredient_id=Ingredients.objects.get(ingredient_name="chocolate chips"), amount=2, unit="cups")
    UserIngredients.objects.create(user_id=user, ingredient_id=Ingredients.objects.get(ingredient_name="baking powder"), amount=1, unit="tsp")

    RecipeIngredients = apps.get_model('recipe_api', 'RecipeIngredients')
    RecipeIngredients.objects.create(recipe_id=newRecipe, ingredient_id=Ingredients.objects.get(ingredient_name="flour"), amount=2, unit="cups")
    RecipeIngredients.objects.create(recipe_id=newRecipe, ingredient_id=Ingredients.objects.get(ingredient_name="salt"), amount=0.75, unit="cups")
    RecipeIngredients.objects.create(recipe_id=newRecipe, ingredient_id=Ingredients.objects.get(ingredient_name="egg"), amount=1, unit="cup")
    RecipeIngredients.objects.create(recipe_id=newRecipe, ingredient_id=Ingredients.objects.get(ingredient_name="chocolate chips"), amount=2, unit="cups")
    RecipeIngredients.objects.create(recipe_id=newRecipe, ingredient_id=Ingredients.objects.get(ingredient_name="baking powder"), amount=1, unit="tsp")

    RecipeSteps = apps.get_model('recipe_api', 'RecipeSteps')
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=1, step_description="Preheat oven to 375 degrees F")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=2, step_description="In a large bowl, cream together the butter, brown sugar, and granulated sugar until smooth")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=3, step_description="Beat in the eggs one at a time, then stir in the vanilla")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=4, step_description="Combine the flour, baking soda, and salt; gradually stir into the creamed mixture")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=5, step_description="Fold in the chocolate chips")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=6, step_description="Drop by rounded spoonfuls onto ungreased cookie sheets")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=7, step_description="Bake for 8 to 10 minutes in the preheated oven, or until golden brown")
    RecipeSteps.objects.create(recipe_id=newRecipe, step_number=8, step_description="Let cookies cool on baking sheet for 5 minutes before transferring to a wire rack to cool completely")

class Migration(migrations.Migration):

    dependencies = [
        ('recipe_api', '0005_merge_20240215_1705'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
